var _TYPES = {
	def: "/image/types/file.gif",

	fon: "/image/types/font.gif",
	pfm: "/image/types/font.gif",
	ttc: "/image/types/font.gif",
	ttf: "/image/types/font.gif",
	chm: "/image/types/chm.gif",
	hlp: "/image/types/hlp.gif",

	bmp: "/image/types/bmp.gif",
	dib: "/image/types/bmp.gif",
	jfif: "/image/types/jpg.gif",
	jpe: "/image/types/jpg.gif",
	jpeg: "/image/types/jpg.gif",	
	jpg: "/image/types/jpg.gif",
	tif: "/image/types/tif.gif",
	tiff: "/image/types/tif.gif",
	svg: "/image/types/image.gif",
	emf: "/image/types/image.gif",
	gif: "/image/types/image.gif",
	png: "/image/types/image.gif",
	psd: "/image/types/image.gif",
	dwg: "/image/types/image.gif",
	cdr: "/image/types/image.gif",
	wmp: "/image/types/image.gif",
	ico: "/image/types/image.gif",
	
	xml: "/image/types/xml.gif",
	biz: "/image/types/xml.gif",
	cml: "/image/types/xml.gif",
	dcd: "/image/types/xml.gif",
	dtd: "/image/types/xml.gif",
	ent: "/image/types/xml.gif",
	fo: "/image/types/xml.gif",
	math: "/image/types/xml.gif",
	mml: "/image/types/xml.gif",
	mtx: "/image/types/xml.gif",
	rdf: "/image/types/xml.gif",
	spp: "/image/types/xml.gif",
	svg: "/image/types/xml.gif",
	tld: "/image/types/xml.gif",
	tsd: "/image/types/xml.gif",
	vml: "/image/types/xml.gif",
	vxml: "/image/types/xml.gif",
	wsdl: "/image/types/xml.gif",
	xdr: "/image/types/xml.gif",
	xq: "/image/types/xml.gif",
	xql: "/image/types/xml.gif",
	xquery: "/image/types/xml.gif",
	xsd: "/image/types/xml.gif",
	
	xsl: "/image/types/xsl.gif",
	xslt: "/image/types/xsl.gif",
	css: "/image/types/style.gif",

	mdl: "/image/types/mdl.gif",
	cat: "/image/types/cat.gif",
	cdm: "/image/types/cdm.gif",
	bpm: "/image/types/bpm.gif",
	pdm: "/image/types/pdm.gif",
	apm: "/image/types/pdm.gif",
	pdx: "/image/types/pdx.gif",

	pdf: "/image/types/pdf.gif",
	
	mpp: "/image/types/mpp.gif",
	mdb: "/image/types/mdb.gif",
	mde: "/image/types/mde.gif",
	pps: "/image/types/pps.gif",
	ppt: "/image/types/ppt.gif",
	pub: "/image/types/pub.gif",
	vdx: "/image/types/vsd.gif",
	vsd: "/image/types/vsd.gif",
	doc: "/image/types/word.gif",
	xlb: "/image/types/excel.gif",
	xls: "/image/types/excel.gif",
	rtf: "/image/types/word.gif",

	js: "/image/types/script.gif",
	jse: "/image/types/script.gif",
	vbe: "/image/types/script.gif",
	vbs: "/image/types/script.gif",
	wsf: "/image/types/script.gif",
	wsh: "/image/types/script.gif",

	swf: "/image/types/flash.gif",
	flv: "/image/types/flash.gif",
	
	asf: "/image/types/media.gif",
	avi: "/image/types/media.gif",
	cda: "/image/types/media.gif",
	m3u: "/image/types/media.gif",
	mid: "/image/types/media.gif",
	midi: "/image/types/media.gif",
	mp1: "/image/types/media.gif",
	mp2: "/image/types/media.gif",
	mp3: "/image/types/media.gif",
	mp4: "/image/types/media.gif",
	mpa: "/image/types/media.gif",
	mpe: "/image/types/media.gif",
	mpeg: "/image/types/media.gif",
	mpg: "/image/types/media.gif",
	rmi: "/image/types/media.gif",
	wav: "/image/types/media.gif",
	wm: "/image/types/media.gif",
	wma: "/image/types/media.gif",
	wmv: "/image/types/media.gif",
	dat: "/image/types/media.gif",
	ra: "/image/types/media.gif",
	ram: "/image/types/media.gif",
	rm: "/image/types/media.gif",
	rmvb: "/image/types/media.gif",

	ace: "/image/types/zip.gif",
	arj: "/image/types/zip.gif",
	bz: "/image/types/zip.gif",
	bz2: "/image/types/zip.gif",
	cab: "/image/types/zip.gif",
	gz: "/image/types/zip.gif",
	iso: "/image/types/zip.gif",
	jar: "/image/types/zip.gif",
	lzh: "/image/types/zip.gif",
	rar: "/image/types/zip.gif",
	tar: "/image/types/zip.gif",
	taz: "/image/types/zip.gif",
	taz2: "/image/types/zip.gif",
	tbz: "/image/types/zip.gif",
	tgz: "/image/types/zip.gif",
	uu: "/image/types/zip.gif",
	uue: "/image/types/zip.gif",
	war: "/image/types/zip.gif",
	xxe: "/image/types/zip.gif",
	z: "/image/types/zip.gif",
	zip: "/image/types/zip.gif",

	conf: "/image/types/text.gif",
	dic: "/image/types/text.gif",
	exc: "/image/types/text.gif",
	java: "/image/types/text.gif",
	log: "/image/types/text.gif",
	scp: "/image/types/text.gif",
	txt: "/image/types/text.gif",
	wtx: "/image/types/text.gif",

	tux: "/image/types/tux.gif"
};
